version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    environment:
      YARN_VERSION: 1.15.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Upgrade yarn
          command: |
            if [[ $(yarn --version) != "${YARN_VERSION}" ]]; then
              curl -o- -L https://yarnpkg.com/install.sh | sh -s -- --version ${YARN_VERSION}
              echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
            fi

      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

      - run: yarn bsb:build

      - run: yarn test

      - run: yarn build

      - store_artifacts:
          path: .next/report.html
          destination: client/report.html

      - store_artifacts:
          path: .next/server/report.html
          destination: server/report.html

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: simon-kjellberg
