version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

      - run: yarn test

      - run: yarn build

      - run: yarn bundlesize

      - store_artifacts:
          path: .next/report.html
          destination: client/report.html

      - store_artifacts:
          path: .next/server/report.html
          destination: server/report.html

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
