name: CI
on: [push]
jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          entrypoint: yarn
          args: install
      - name: Build
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        env:
          CI: 'true'
          PACKTRACKER_PROJECT_TOKEN: ${{ secrets.PACKTRACKER_PROJECT_TOKEN }}
        with:
          entrypoint: yarn
          args: build
      - name: Test
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          entrypoint: yarn
          args: test
