name: CI
on: [push]
jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
        env:
          CI: 'true'
          PACKTRACKER_PROJECT_TOKEN: ${{ secrets.PACKTRACKER_PROJECT_TOKEN }}
      - name: Test
        run: yarn test
